const Product = require('../models/Product');

const products = [
  // ==================== CLEANSERS (5) ====================
  {
    name: 'Cetaphil Gentle Skin Cleanser',
    description: 'A cult-favorite ultra-gentle, non-foaming cleanser that removes impurities without stripping the skin barrier. Ideal for sensitive and dry skin types with a soap-free, fragrance-free formula.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    category: 'cleanser',
    skinType: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'redness'],
    ingredients: ['water', 'glycerin', 'cetyl alcohol', 'panthenol'],
    stock: 120,
    rating: 4.7,
    numReviews: 243,
    isFeatured: true,
  },
  {
    name: 'COSRX Low pH Good Morning Gel Cleanser',
    description: 'A mildly acidic (pH 5.5) gel cleanser with tea tree oil and BHA that gently removes impurities while balancing the skin barrier — perfect for morning routines.',
    price: 950,
    compareAtPrice: 1200,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    category: 'cleanser',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'pores'],
    ingredients: ['tea tree oil', 'BHA', 'centella asiatica', 'glycerin'],
    stock: 95,
    rating: 4.6,
    numReviews: 187,
    isFeatured: false,
  },
  {
    name: 'Beauty of Joseon Green Plum Refreshing Cleanser',
    description: 'A gentle gel cleanser made with 24% green plum water and mung bean extract. Deeply hydrates while cleansing, leaving skin refreshed and plump with a healthy glow.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    category: 'cleanser',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'pores'],
    ingredients: ['green plum water 24%', 'mung bean extract', 'glycerin', 'betaine'],
    stock: 78,
    rating: 4.5,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'Bioderma Sensibio H2O Micellar Water',
    description: 'The iconic micellar water that removes makeup, sunscreen, and impurities in one gentle swipe. A dermatologist favorite for sensitive and reactive skin — no rinsing required.',
    price: 899,
    compareAtPrice: 1099,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    category: 'cleanser',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['micellar technology', 'cucumber extract', 'glycerin', 'mannitol'],
    stock: 160,
    rating: 4.8,
    numReviews: 210,
    isFeatured: true,
  },
  {
    name: 'Anua Heartleaf Pore Control Cleansing Oil',
    description: 'A lightweight cleansing oil with heartleaf extract that gently melts away blackheads, sebum, and waterproof makeup. Non-comedogenic and suitable for acne-prone skin.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    category: 'cleanser',
    skinType: ['oily', 'combination', 'normal'],
    concerns: ['pores', 'acne', 'dullness'],
    ingredients: ['heartleaf extract', 'jojoba oil', 'sunflower seed oil', 'vitamin E'],
    stock: 70,
    rating: 4.7,
    numReviews: 134,
    isFeatured: true,
  },

  // ==================== MOISTURIZERS (5) ====================
  {
    name: 'CeraVe Moisturizing Cream (Tub)',
    description: 'A rich, non-greasy moisturizer with 3 essential ceramides and hyaluronic acid. Restores the skin barrier and provides 24-hour hydration. Accepted by the National Eczema Association.',
    price: 1899,
    compareAtPrice: 2299,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    category: 'moisturizer',
    skinType: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'redness', 'uneven-texture'],
    ingredients: ['ceramides NP/AP/EOP', 'hyaluronic acid', 'glycerin', 'cholesterol'],
    stock: 85,
    rating: 4.8,
    numReviews: 312,
    isFeatured: true,
  },
  {
    name: 'Minimalist Sepicalm 3% + Oats Moisturizer',
    description: 'A lightweight, soothing face moisturizer for oily and acne-prone skin. Sepicalm and oat extract calm inflammation while amino acids repair the barrier without clogging pores.',
    price: 449,
    compareAtPrice: 549,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    category: 'moisturizer',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'redness', 'pores'],
    ingredients: ['sepicalm 3%', 'oats extract', 'amino acids', 'glycerin'],
    stock: 110,
    rating: 4.5,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Etude SoonJung 2x Barrier Intensive Cream',
    description: 'A hypoallergenic, panthenol-rich cream that deeply soothes and repairs the skin barrier. Free of fragrance, parabens, and alcohol — perfect for extremely sensitive skin.',
    price: 1699,
    compareAtPrice: 2099,
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600'],
    category: 'moisturizer',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['panthenol 10%', 'madecassoside', 'green tea extract', 'shea butter'],
    stock: 65,
    rating: 4.7,
    numReviews: 178,
    isFeatured: true,
  },
  {
    name: 'Aqualogica Glow+ Dewy Moisturizer',
    description: 'A water-locking gel moisturizer with papaya extract and vitamin C. Provides SPF-like protection against blue light while delivering a dewy, glass-skin finish for all skin types.',
    price: 499,
    compareAtPrice: 599,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    category: 'moisturizer',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dullness', 'dryness'],
    ingredients: ['papaya extract', 'vitamin C', 'hyaluronic acid', 'niacinamide'],
    stock: 130,
    rating: 4.4,
    numReviews: 165,
    isFeatured: false,
  },
  {
    name: 'Round Lab 1025 Dokdo Cream',
    description: 'A rich moisturizer infused with deep seawater from Dokdo Island and panthenol. Strengthens the skin barrier, delivers intense hydration, and leaves a smooth, non-sticky finish.',
    price: 1899,
    compareAtPrice: 2299,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    category: 'moisturizer',
    skinType: ['dry', 'normal', 'sensitive'],
    concerns: ['dryness', 'redness'],
    ingredients: ['deep seawater', 'panthenol', 'betaine', 'allantoin'],
    stock: 60,
    rating: 4.6,
    numReviews: 142,
    isFeatured: false,
  },

  // ==================== SERUMS (6) ====================
  {
    name: 'The Ordinary Vitamin C Suspension 23% + HA Spheres',
    description: 'A high-potency 23% L-ascorbic acid suspension with hyaluronic acid spheres. Dramatically brightens skin, targets dark spots, and smooths uneven texture over time.',
    price: 899,
    compareAtPrice: 1099,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    category: 'serum',
    skinType: ['normal', 'combination'],
    concerns: ['dark-spots', 'dullness', 'uneven-texture'],
    ingredients: ['L-ascorbic acid 23%', 'hyaluronic acid spheres', 'squalane'],
    stock: 72,
    rating: 4.3,
    numReviews: 421,
    isFeatured: true,
  },
  {
    name: 'The Ordinary Hyaluronic Acid 2% + B5',
    description: 'A deeply hydrating serum with low, medium, and high molecular weight HA plus vitamin B5. Plumps skin, reduces fine lines, and supports barrier function for all skin types.',
    price: 799,
    compareAtPrice: 999,
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600'],
    category: 'serum',
    skinType: ['dry', 'normal', 'sensitive', 'combination'],
    concerns: ['dryness', 'aging', 'redness'],
    ingredients: ['hyaluronic acid 2%', 'vitamin B5', 'glycerin', 'trehalose'],
    stock: 100,
    rating: 4.6,
    numReviews: 356,
    isFeatured: true,
  },
  {
    name: 'Minimalist Retinol 0.6% Face Serum',
    description: 'An advanced retinol serum with 0.6% retinol, coenzyme Q10, and squalane. Targets fine lines, wrinkles, and uneven skin texture with minimal irritation using time-release technology.',
    price: 699,
    compareAtPrice: 849,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    category: 'serum',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['aging', 'acne', 'pores', 'uneven-texture'],
    ingredients: ['retinol 0.6%', 'coenzyme Q10', 'squalane', 'tocopherol'],
    stock: 58,
    rating: 4.5,
    numReviews: 289,
    isFeatured: false,
  },
  {
    name: 'COSRX Advanced Snail 96 Mucin Power Essence',
    description: 'The viral snail mucin essence with 96% snail secretion filtrate. Repairs damaged skin, fades scars, boosts elasticity, and delivers deep hydration for a glass-skin glow.',
    price: 1450,
    compareAtPrice: 1800,
    images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600'],
    category: 'serum',
    skinType: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['uneven-texture', 'dryness', 'aging', 'dark-spots'],
    ingredients: ['snail mucin 96%', 'hyaluronic acid', 'panthenol', 'allantoin'],
    stock: 50,
    rating: 4.8,
    numReviews: 312,
    isFeatured: true,
  },
  {
    name: 'Deconstruct Peptide Serum 5% + Niacinamide',
    description: 'A multi-peptide serum combining Matrixyl 3000, Argireline, and niacinamide. Visibly firms and lifts skin, reduces expression lines, and strengthens the skin barrier.',
    price: 599,
    compareAtPrice: 749,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    category: 'serum',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'uneven-texture', 'dullness'],
    ingredients: ['peptides 5%', 'niacinamide 2%', 'hyaluronic acid', 'ceramides'],
    stock: 55,
    rating: 4.4,
    numReviews: 178,
    isFeatured: false,
  },
  {
    name: 'Some By Mi AHA BHA PHA 30 Days Miracle Serum',
    description: 'The legendary Korean serum with AHA, BHA, and PHA for gentle daily exfoliation. Clears acne, fades dark spots, tightens pores, and reveals glass skin in 30 days.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    category: 'serum',
    skinType: ['combination', 'oily', 'normal'],
    concerns: ['acne', 'pores', 'dark-spots', 'dullness'],
    ingredients: ['AHA', 'BHA', 'PHA', 'centella asiatica', 'niacinamide'],
    stock: 80,
    rating: 4.5,
    numReviews: 212,
    isFeatured: false,
  },

  // ==================== TONERS (4) ====================
  {
    name: 'Plum Green Tea Alcohol-Free Toner',
    description: 'An alcohol-free toner with green tea extract, glycolic acid, and niacinamide. Controls excess oil, prevents breakouts, and tightens pores without over-drying the skin.',
    price: 399,
    compareAtPrice: 499,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    category: 'toner',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'dullness'],
    ingredients: ['green tea extract', 'glycolic acid', 'niacinamide', 'glycerin'],
    stock: 140,
    rating: 4.3,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'Beauty of Joseon Ginseng Essence Water',
    description: 'An essence-water hybrid toner with 80% ginseng root water and niacinamide. Deeply nourishes, brightens complexion, and provides anti-aging benefits for a radiant glow.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    category: 'toner',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dullness', 'aging', 'dryness'],
    ingredients: ['ginseng root water 80%', 'niacinamide', 'squalane', 'panthenol'],
    stock: 105,
    rating: 4.6,
    numReviews: 167,
    isFeatured: true,
  },
  {
    name: 'SKIN1004 Madagascar Centella Toning Toner',
    description: 'A lightweight watery toner with 84% Madagascar centella asiatica extract. Instantly calms redness and irritation while strengthening the skin barrier. Suitable for all skin types.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600'],
    category: 'toner',
    skinType: ['sensitive', 'oily', 'combination', 'normal'],
    concerns: ['redness', 'acne', 'dryness'],
    ingredients: ['centella asiatica 84%', 'hyaluronic acid', 'panthenol', 'betaine'],
    stock: 92,
    rating: 4.7,
    numReviews: 189,
    isFeatured: true,
  },
  {
    name: 'Isntree Green Tea Fresh Toner',
    description: 'A refreshing toner packed with 80% green tea extract from Jeju Island. Controls sebum, soothes inflammation, and provides antioxidant protection for a clear, balanced complexion.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600'],
    category: 'toner',
    skinType: ['oily', 'combination', 'sensitive'],
    concerns: ['pores', 'redness', 'dullness'],
    ingredients: ['green tea extract 80%', 'hyaluronic acid', 'beta-glucan', 'allantoin'],
    stock: 88,
    rating: 4.5,
    numReviews: 203,
    isFeatured: false,
  },

  // ==================== SUNSCREENS (4) ====================
  {
    name: 'Aqualogica Glow+ Dewy Sunscreen SPF 50 PA++++',
    description: 'A water-light gel sunscreen with SPF 50 PA++++ and zero white cast. Infused with papaya and vitamin C to brighten and protect. Blue light protection included.',
    price: 399,
    compareAtPrice: 499,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    category: 'sunscreen',
    skinType: ['oily', 'combination', 'normal'],
    concerns: ['aging', 'dark-spots', 'dullness'],
    ingredients: ['vitamin C', 'papaya extract', 'hyaluronic acid', 'niacinamide'],
    stock: 150,
    rating: 4.4,
    numReviews: 487,
    isFeatured: true,
  },
  {
    name: 'Neutrogena UltraSheer Dry Touch Sunscreen SPF 50+',
    description: 'A dermatologist-recommended lightweight sunscreen with Dry-Touch technology. Provides broad spectrum UVA/UVB protection with a matte, non-greasy finish. PABA-free.',
    price: 699,
    compareAtPrice: 799,
    images: ['https://images.unsplash.com/photo-1556229162-5c63ed9c4efb?w=600'],
    category: 'sunscreen',
    skinType: ['normal', 'dry', 'combination', 'oily'],
    concerns: ['aging', 'dark-spots'],
    ingredients: ['avobenzone', 'homosalate', 'octisalate', 'heliplex technology'],
    stock: 75,
    rating: 4.6,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Beauty of Joseon Relief Sun Rice + Probiotics SPF 50',
    description: 'A viral cult-favorite Korean sunscreen with rice extract and probiotics. Creamy, lightweight texture with zero white cast. Nourishes skin while providing SPF 50 PA++++ protection.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    category: 'sunscreen',
    skinType: ['normal', 'dry', 'sensitive', 'combination'],
    concerns: ['aging', 'dryness', 'dullness'],
    ingredients: ['rice extract 30%', 'probiotics', 'niacinamide', 'glycerin'],
    stock: 120,
    rating: 4.8,
    numReviews: 356,
    isFeatured: true,
  },
  {
    name: 'Simple Kind to Skin Protecting Moisturizer SPF 30',
    description: 'A gentle 2-in-1 daily moisturizer with SPF 30 and no artificial perfumes or colors. Perfect for sensitive skin, the lightweight formula hydrates and protects in one easy step.',
    price: 449,
    compareAtPrice: 549,
    images: ['https://images.unsplash.com/photo-1556229162-5c63ed9c4efb?w=600'],
    category: 'sunscreen',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['aging', 'dryness', 'redness'],
    ingredients: ['glycerin', 'ceramides', 'bisabolol', 'SPF 30 filters'],
    stock: 140,
    rating: 4.3,
    numReviews: 189,
    isFeatured: false,
  },

  // ==================== MASKS (5) ====================
  {
    name: 'Pilgrim Korean White Clay Bubble Mask',
    description: 'A fun oxygen-bubble clay mask with white kaolin clay and volcanic ash. Bubbles up to deep-cleanse pores, remove blackheads, and leave skin bright and detoxified.',
    price: 550,
    compareAtPrice: 699,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    category: 'mask',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['pores', 'acne', 'dullness'],
    ingredients: ['white kaolin clay', 'volcanic ash', 'aloe vera', 'panthenol'],
    stock: 90,
    rating: 4.4,
    numReviews: 176,
    isFeatured: false,
  },
  {
    name: 'COSRX Ultimate Nourishing Rice Overnight Spa Mask',
    description: 'A cult-favorite overnight sleeping mask with 68% rice extract. Deeply nourishes and brightens dull skin while you sleep. Wake up to plump, glowing, glass skin.',
    price: 1350,
    compareAtPrice: 1650,
    images: ['https://images.unsplash.com/photo-1607434472257-d9f8e57a643d?w=600'],
    category: 'mask',
    skinType: ['dry', 'normal', 'combination'],
    concerns: ['dryness', 'dullness', 'aging'],
    ingredients: ['rice extract 68%', 'niacinamide', 'hyaluronic acid', 'vitamin E'],
    stock: 82,
    rating: 4.7,
    numReviews: 234,
    isFeatured: true,
  },
  {
    name: 'Plum Green Tea Clear Face Mask',
    description: 'A creamy clay mask with green tea extracts and kaolin clay. Controls excess oil, fights acne-causing bacteria, and soothes inflammation — perfect for oily and acne-prone skin.',
    price: 475,
    compareAtPrice: 575,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    category: 'mask',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'dullness'],
    ingredients: ['green tea extract', 'kaolin clay', 'salicylic acid', 'aloe vera'],
    stock: 95,
    rating: 4.3,
    numReviews: 154,
    isFeatured: false,
  },
  {
    name: 'Faces Canada Vitamin C Sheet Mask',
    description: 'A bio-cellulose sheet mask drenched in vitamin C serum and hyaluronic acid. Instantly brightens dull skin, hydrates deeply, and restores radiance in just 15 minutes.',
    price: 199,
    compareAtPrice: 249,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    category: 'mask',
    skinType: ['normal', 'dry', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'dryness'],
    ingredients: ['vitamin C', 'hyaluronic acid', 'glycerin', 'niacinamide'],
    stock: 180,
    rating: 4.2,
    numReviews: 267,
    isFeatured: false,
  },
  {
    name: 'Isntree Real Rose Calming Mask',
    description: 'A soothing sheet mask infused with real rose petals and damask rose water. Calms redness, deeply hydrates, and leaves skin petal-soft with a radiant rosy glow.',
    price: 250,
    compareAtPrice: 300,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    category: 'mask',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness', 'dullness'],
    ingredients: ['damask rose water', 'rose petals', 'hyaluronic acid', 'panthenol'],
    stock: 100,
    rating: 4.5,
    numReviews: 189,
    isFeatured: false,
  },

  // ==================== EYE CARE (4) ====================
  {
    name: 'Minimalist Vitamin K + Retinal 01% Eye Cream',
    description: 'A innovative eye cream with Vitamin K and retinal for dark circles and fine lines. Reduces under-eye discoloration, puffiness, and crow\'s feet without irritation.',
    price: 649,
    compareAtPrice: 799,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'dark-spots', 'dullness'],
    ingredients: ['vitamin K', 'retinal 0.1%', 'peptides', 'hyaluronic acid'],
    stock: 68,
    rating: 4.4,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Pilgrim Retinol Under Eye Cream',
    description: 'A gentle retinol-infused eye cream with bakuchiol and peptides. Targets crow\'s feet, fine lines, and dark circles around the delicate eye area. Time-release formula for minimal irritation.',
    price: 599,
    compareAtPrice: 749,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'dullness'],
    ingredients: ['retinol', 'bakuchiol', 'peptides', 'caffeine'],
    stock: 55,
    rating: 4.3,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'Foxtale Brightening Under Eye Cream',
    description: 'A vitamin C + niacinamide eye cream that targets stubborn dark circles. Light-reflecting pearls instantly brighten while the formula works long-term on pigmentation.',
    price: 549,
    compareAtPrice: 699,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dark-spots', 'dullness', 'aging'],
    ingredients: ['vitamin C', 'niacinamide', 'kojic acid', 'caffeine'],
    stock: 62,
    rating: 4.5,
    numReviews: 110,
    isFeatured: false,
  },
  {
    name: 'Plum Vitamin C Under Eye Cream',
    description: 'A lightweight eye cream enriched with 3% vitamin C and Japanese mandarin extract. Brightens dark circles, depuffs, and smooths fine lines for refreshed, awake-looking eyes.',
    price: 449,
    compareAtPrice: 549,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    category: 'eye-care',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['dullness', 'aging'],
    ingredients: ['vitamin C 3%', 'Japanese mandarin', 'hyaluronic acid', 'caffeine'],
    stock: 100,
    rating: 4.2,
    numReviews: 98,
    isFeatured: false,
  },

  // ==================== LIP CARE (4) ====================
  {
    name: 'Foxtale Lip Lightening Balm SPF 30',
    description: 'A tinted lip balm with SPF 30 and tranexamic acid. Lightens pigmented lips over time while providing sun protection and a sheer pink tint that adapts to your pH.',
    price: 399,
    compareAtPrice: 499,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    category: 'lip-care',
    skinType: ['normal', 'dry', 'oily', 'combination'],
    concerns: ['dark-spots', 'dryness'],
    ingredients: ['tranexamic acid', 'SPF 30', 'shea butter', 'vitamin E'],
    stock: 200,
    rating: 4.4,
    numReviews: 89,
    isFeatured: false,
  },
  {
    name: 'COSRX Ceramide Lip Butter Sleeping Mask',
    description: 'A rich overnight lip sleeping mask with ceramides and shea butter. Melts away dead skin while you sleep, delivering plump, baby-soft lips by morning. Vanilla-scented.',
    price: 850,
    compareAtPrice: 1050,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    category: 'lip-care',
    skinType: ['normal', 'dry', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['ceramides', 'shea butter', 'hyaluronic acid', 'vitamin E'],
    stock: 150,
    rating: 4.7,
    numReviews: 215,
    isFeatured: true,
  },
  {
    name: 'Faces Canada Lip Crayon & Balm Duo',
    description: 'A hydrating lip crayon with built-in balm in a single twist-up stick. Delivers vibrant color with a glossy finish while keeping lips moisturized for hours.',
    price: 549,
    compareAtPrice: 699,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    category: 'lip-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dryness'],
    ingredients: ['shea butter', 'jojoba oil', 'vitamin E', 'mineral pigments'],
    stock: 175,
    rating: 4.3,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'Pilgrim Squalane Glow Lip Sleeping Mask',
    description: 'An overnight lip mask with squalane, vitamin C, and berry complex. Exfoliates dead skin, deeply nourishes, and reveals naturally pink, plump lips. Cushiony balm texture.',
    price: 475,
    compareAtPrice: 599,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    category: 'lip-care',
    skinType: ['normal', 'dry'],
    concerns: ['dryness', 'dullness'],
    ingredients: ['squalane', 'vitamin C', 'berry complex', 'shea butter'],
    stock: 85,
    rating: 4.5,
    numReviews: 123,
    isFeatured: false,
  },

  // ==================== BODY CARE (5) ====================
  {
    name: 'Suganda 10% AHA + 1% BHA Body Lotion',
    description: 'A body smoothing lotion with 10% AHA and 1% BHA. Exfoliates rough bumps, keratosis pilaris, and strawberry skin. Leaves skin silky-smooth with continued use.',
    price: 649,
    compareAtPrice: 799,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    category: 'body-care',
    skinType: ['dry', 'normal'],
    concerns: ['uneven-texture', 'dryness'],
    ingredients: ['lactic acid', 'glycolic acid', 'salicylic acid 1%', 'shea butter'],
    stock: 75,
    rating: 4.5,
    numReviews: 167,
    isFeatured: false,
  },
  {
    name: 'Plum BodyLovin\' Vanilla Vibes Body Butter',
    description: 'A whipped, ultra-rich body butter with shea, cocoa butter, and vanilla. Intensely moisturizes for 48 hours with a warm, comforting vanilla fragrance. For normal to very dry skin.',
    price: 525,
    compareAtPrice: 649,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    category: 'body-care',
    skinType: ['dry', 'normal'],
    concerns: ['dryness'],
    ingredients: ['shea butter', 'cocoa butter', 'coconut oil', 'vitamin E'],
    stock: 100,
    rating: 4.6,
    numReviews: 234,
    isFeatured: true,
  },
  {
    name: 'Aqualogica Radiance+ Body Sunscreen SPF 50',
    description: 'A lightweight, non-greasy body sunscreen spray with broad spectrum SPF 50. Quick-dry, water-resistant, and enriched with hyaluronic acid for hydrated skin all day.',
    price: 599,
    compareAtPrice: 749,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    category: 'body-care',
    skinType: ['normal', 'oily', 'dry', 'combination'],
    concerns: ['aging', 'dark-spots'],
    ingredients: ['hyaluronic acid', 'vitamin C', 'aloe vera', 'SPF 50 filters'],
    stock: 115,
    rating: 4.3,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Simple Kind to Skin Hydrating Hand Cream',
    description: 'A concentrated hand cream with glycerin, shea butter, and ceramides. Repairs dry cracked hands, strengthens nails, and restores cuticles. Non-greasy and fast-absorbing.',
    price: 249,
    compareAtPrice: 299,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    category: 'body-care',
    skinType: ['normal', 'dry', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['glycerin', 'shea butter', 'ceramides', 'allantoin'],
    stock: 160,
    rating: 4.4,
    numReviews: 178,
    isFeatured: false,
  },
  {
    name: 'Pilgrim Colombian Coffee Body Scrub',
    description: 'An invigorating body scrub with Arabica coffee grounds, coconut oil, and sea salt. Buffs away dead skin, stimulates circulation, and helps reduce cellulite. Smells like a café latte.',
    price: 449,
    compareAtPrice: 549,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    category: 'body-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['uneven-texture', 'dullness'],
    ingredients: ['colombian coffee grounds', 'coconut oil', 'sea salt', 'almond oil'],
    stock: 90,
    rating: 4.5,
    numReviews: 167,
    isFeatured: false,
  },

  // ==================== FACE CARE (5) ====================
  {
    name: 'Suganda Squalane Rosehip Face Oil',
    description: 'A lightweight, fast-absorbing face oil with cold-pressed rosehip, squalane, and jojoba. Rich in essential fatty acids that nourish and restore radiance without clogging pores.',
    price: 749,
    compareAtPrice: 899,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    category: 'face-care',
    skinType: ['dry', 'normal', 'combination'],
    concerns: ['dullness', 'dryness', 'uneven-texture'],
    ingredients: ['rosehip oil', 'squalane', 'jojoba oil', 'vitamin E'],
    stock: 72,
    rating: 4.6,
    numReviews: 189,
    isFeatured: true,
  },
  {
    name: 'Simple Soothing Facial Toner Mist',
    description: 'A refreshing alcohol-free face mist with chamomile, allantoin, and glycerin. Instantly soothes irritated skin, sets makeup, and provides a hydration boost anytime, anywhere.',
    price: 299,
    compareAtPrice: 375,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    category: 'face-care',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['chamomile extract', 'allantoin', 'glycerin', 'panthenol'],
    stock: 140,
    rating: 4.3,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Cetaphil Gentle Exfoliating Face Scrub',
    description: 'A finely milled micro-fine scrub with bamboo extract and vitamins B5 & E. Buffs away dead skin cells without micro-tears. Gentle enough for daily use on sensitive skin.',
    price: 649,
    compareAtPrice: 799,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    category: 'face-care',
    skinType: ['normal', 'combination', 'sensitive'],
    concerns: ['uneven-texture', 'dullness'],
    ingredients: ['bamboo micro-particles', 'vitamin B5', 'vitamin E', 'glycerin'],
    stock: 95,
    rating: 4.4,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'The Derma Co 1% Salicylic Acid Face Wash with CICA',
    description: 'A gentle exfoliating face wash with 1% salicylic acid and centella asiatica. Deeply cleanses pores, controls acne, and prevents breakouts while soothing inflammation.',
    price: 349,
    compareAtPrice: 449,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    category: 'face-care',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'dullness'],
    ingredients: ['salicylic acid 1%', 'centella asiatica', 'niacinamide', 'aloe vera'],
    stock: 110,
    rating: 4.4,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Deconstruct Face Moisturizer - Vitamin C + Niacinamide',
    description: 'A lightweight daily face moisturizer with 5% vitamin C and 2% niacinamide. Brightens complexion, evens skin tone, and provides all-day hydration with a non-greasy dewy finish.',
    price: 429,
    compareAtPrice: 549,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    category: 'face-care',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'uneven-texture'],
    ingredients: ['vitamin C 5%', 'niacinamide 2%', 'hyaluronic acid', 'glycerin'],
    stock: 80,
    rating: 4.3,
    numReviews: 145,
    isFeatured: false,
  },

  // ==================== SETS & BUNDLES (4) ====================
  {
    name: 'CeraVe Daily Skincare Routine Set',
    description: 'The complete dermatologist-recommended routine: Hydrating Facial Cleanser (88ml), AM Facial Moisturizing Lotion SPF 30, and PM Facial Moisturizing Lotion. Everything you need for healthy skin.',
    price: 2499,
    compareAtPrice: 3199,
    images: ['https://images.unsplash.com/photo-1580870069867-74c57ee9bb07?w=600'],
    category: 'set',
    skinType: ['normal', 'dry', 'sensitive'],
    concerns: ['dryness', 'aging'],
    ingredients: ['multiple'],
    stock: 40,
    rating: 4.8,
    numReviews: 312,
    isFeatured: true,
  },
  {
    name: 'Minimalist Advanced Anti-Aging Kit',
    description: 'A complete anti-aging duo: Retinol 0.6% Face Serum + Vitamin C 10% Face Serum. The ultimate night and day routine for smoother, firmer, brighter skin. For beginners to actives.',
    price: 1299,
    compareAtPrice: 1549,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    category: 'set',
    skinType: ['normal', 'combination'],
    concerns: ['aging', 'uneven-texture', 'dullness'],
    ingredients: ['multiple'],
    stock: 35,
    rating: 4.6,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'The Ordinary Brightening Trio Set',
    description: 'Three cult favorites in one box: Vitamin C Suspension 23% + HA (30ml), Niacinamide 10% + Zinc 1% (30ml), and Hyaluronic Acid 2% + B5 (30ml). The ultimate glow-up routine.',
    price: 2199,
    compareAtPrice: 2799,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    category: 'set',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'aging'],
    ingredients: ['multiple'],
    stock: 50,
    rating: 4.7,
    numReviews: 89,
    isFeatured: true,
  },
  {
    name: 'COSRX Snail Mucin Hydration Kit',
    description: 'The viral snail duo: Advanced Snail 96 Mucin Power Essence (100ml) + Advanced Snail 92 All in One Cream (100g). Deeply repairs, hydrates, and restores the skin barrier.',
    price: 2699,
    compareAtPrice: 3399,
    images: ['https://images.unsplash.com/photo-1580870069867-74c57ee9bb07?w=600'],
    category: 'set',
    skinType: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['uneven-texture', 'dryness', 'aging'],
    ingredients: ['multiple'],
    stock: 55,
    rating: 4.9,
    numReviews: 98,
    isFeatured: true,
  },
];

const seedProducts = async () => {
  try {
    const count = await Product.countDocuments();
    if (count > 0) {
      await Product.deleteMany({});
      console.log(`Cleared ${count} existing products before re-seeding...`);
    }

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} skincare products successfully.`);
  } catch (error) {
    console.error(`Seeding error: ${error.message}`);
  }
};

module.exports = seedProducts;
