const Product = require('../models/Product');

const products = [
  // ==================== CLEANSERS ====================
  {
    name: 'Gentle Hydrating Cleanser',
    description: 'A creamy, non-foaming cleanser that removes impurities without stripping the skin\'s natural moisture barrier. Infused with ceramides and hyaluronic acid for deep hydration.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    brand: 'Cetaphil',
    category: 'cleanser',
    skinType: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'redness'],
    ingredients: ['ceramides', 'hyaluronic acid', 'glycerin', 'niacinamide'],
    stock: 120,
    rating: 4.7,
    numReviews: 243,
    isFeatured: true,
  },
  {
    name: 'Purifying Foam Cleanser',
    description: 'A lightweight foaming cleanser with salicylic acid and tea tree oil. Deeply cleanses pores, controls excess oil, and helps prevent breakouts without over-drying.',
    price: 1099,
    compareAtPrice: 1399,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    brand: 'The Derma Co',
    category: 'cleanser',
    skinType: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'dullness'],
    ingredients: ['salicylic acid 2%', 'tea tree oil', 'witch hazel', 'aloe vera'],
    stock: 95,
    rating: 4.5,
    numReviews: 187,
    isFeatured: false,
  },
  {
    name: 'Vitamin C Brightening Wash',
    description: 'A radiance-boosting gel cleanser packed with vitamin C, turmeric, and fruit enzymes. Gently exfoliates and brightens dull, tired-looking skin.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    brand: 'Pilgrim',
    category: 'cleanser',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'uneven-texture'],
    ingredients: ['vitamin C', 'turmeric extract', 'papaya enzymes', 'green tea'],
    stock: 78,
    rating: 4.6,
    numReviews: 156,
    isFeatured: true,
  },
  {
    name: 'Micellar Water Cleanser',
    description: 'Gentle micellar water with chamomile and glycerin that removes makeup, sunscreen, and impurities in one swipe. No rinsing required — perfect for sensitive skin.',
    price: 899,
    compareAtPrice: 1099,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    brand: 'Bioderma',
    category: 'cleanser',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['micellar technology', 'chamomile extract', 'glycerin', 'panthenol'],
    stock: 160,
    rating: 4.4,
    numReviews: 210,
    isFeatured: false,
  },
  {
    name: 'Oil-to-Milk Cleansing Balm',
    description: 'A luxurious sherbet-textured balm that melts into a silky oil to dissolve waterproof makeup and SPF, then emulsifies into a milky cleanser that rinses clean with zero residue.',
    price: 1599,
    compareAtPrice: 1999,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    brand: 'Beauty of Joseon',
    category: 'cleanser',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dullness', 'dryness'],
    ingredients: ['moringa oil', 'vitamin E', 'olive squalane', 'sunflower seed oil'],
    stock: 70,
    rating: 4.8,
    numReviews: 134,
    isFeatured: false,
  },

  // ==================== MOISTURIZERS ====================
  {
    name: 'Ceramide Barrier Repair Cream',
    description: 'A rich, nourishing moisturizer with 5 essential ceramides and peptides. Repairs the skin barrier, locks in moisture for 48 hours, and restores elasticity.',
    price: 1899,
    compareAtPrice: 2299,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    brand: 'CeraVe',
    category: 'moisturizer',
    skinType: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'redness', 'aging'],
    ingredients: ['ceramides NP/AP/EOP', 'peptides', 'shea butter', 'squalane'],
    stock: 85,
    rating: 4.8,
    numReviews: 312,
    isFeatured: true,
  },
  {
    name: 'Oil-Free Mattifying Moisturizer',
    description: 'A lightweight, oil-free gel moisturizer that delivers hydration while controlling shine. Contains niacinamide to minimize pores and even out skin tone.',
    price: 1499,
    compareAtPrice: 1799,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    brand: 'Minimalist',
    category: 'moisturizer',
    skinType: ['oily', 'combination'],
    concerns: ['pores', 'dullness', 'uneven-texture'],
    ingredients: ['niacinamide 5%', 'hyaluronic acid', 'zinc PCA', 'panthenol'],
    stock: 110,
    rating: 4.6,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Collagen Peptide Night Cream',
    description: 'An intensive overnight treatment cream that works while you sleep. Collagen peptides and retinol help reduce fine lines, firm skin, and boost cell turnover.',
    price: 2199,
    compareAtPrice: 2499,
    images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600'],
    brand: 'Foxtale',
    category: 'moisturizer',
    skinType: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'dullness', 'uneven-texture'],
    ingredients: ['collagen peptides', 'retinol 0.3%', 'bakuchiol', 'vitamin E'],
    stock: 65,
    rating: 4.7,
    numReviews: 178,
    isFeatured: true,
  },
  {
    name: 'Water Burst Gel Moisturizer',
    description: 'A refreshing water-based gel moisturizer that instantly cools and hydrates. Hyaluronic acid and aloe vera drench skin in moisture without any greasy feel.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    brand: 'Aqualogica',
    category: 'moisturizer',
    skinType: ['oily', 'combination', 'normal'],
    concerns: ['dryness', 'dullness'],
    ingredients: ['hyaluronic acid', 'aloe vera', 'cucumber extract', 'green tea'],
    stock: 130,
    rating: 4.5,
    numReviews: 165,
    isFeatured: false,
  },
  {
    name: 'Probiotic Skin Rescue Cream',
    description: 'A soothing cream with probiotic lysate, centella asiatica, and oat extract. Strengthens the microbiome, calms irritation, and restores balance to stressed skin.',
    price: 1999,
    compareAtPrice: 2399,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    brand: 'Suganda',
    category: 'moisturizer',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['probiotic lysate', 'centella asiatica', 'oat extract', 'ceramides'],
    stock: 60,
    rating: 4.6,
    numReviews: 142,
    isFeatured: false,
  },

  // ==================== SERUMS ====================
  {
    name: 'Vitamin C 20% Radiance Serum',
    description: 'A powerful antioxidant serum with 20% L-ascorbic acid. Dramatically brightens skin, fades dark spots, and protects against environmental damage.',
    price: 2499,
    compareAtPrice: 2999,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    brand: 'The Ordinary',
    category: 'serum',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dark-spots', 'dullness', 'aging', 'uneven-texture'],
    ingredients: ['L-ascorbic acid 20%', 'ferulic acid', 'vitamin E', 'hyaluronic acid'],
    stock: 72,
    rating: 4.9,
    numReviews: 421,
    isFeatured: true,
  },
  {
    name: 'Hyaluronic Acid 2% + B5',
    description: 'A deeply hydrating serum with ultra-low and high molecular weight hyaluronic acid plus vitamin B5. Plumps skin, reduces fine lines, and supports barrier function.',
    price: 1799,
    compareAtPrice: 2199,
    images: ['https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600'],
    brand: 'The Ordinary',
    category: 'serum',
    skinType: ['dry', 'normal', 'sensitive', 'combination'],
    concerns: ['dryness', 'aging', 'redness'],
    ingredients: ['hyaluronic acid 2%', 'vitamin B5', 'beta-glucan', 'trehalose'],
    stock: 100,
    rating: 4.7,
    numReviews: 356,
    isFeatured: true,
  },
  {
    name: 'Retinol 0.5% Advanced Serum',
    description: 'A time-release retinol serum that smooths wrinkles, refines texture, and clears acne. Encapsulated technology minimizes irritation for nightly use.',
    price: 2799,
    compareAtPrice: 3299,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    brand: 'Minimalist',
    category: 'serum',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['aging', 'acne', 'pores', 'uneven-texture'],
    ingredients: ['retinol 0.5%', 'bakuchiol', 'peptides', 'ceramides'],
    stock: 58,
    rating: 4.6,
    numReviews: 289,
    isFeatured: false,
  },
  {
    name: 'Niacinamide 10% + Zinc',
    description: 'A high-strength niacinamide serum that minimizes pores, controls oil, and calms redness. Zinc PCA provides antibacterial benefits for acne-prone skin.',
    price: 1599,
    compareAtPrice: 1899,
    images: ['https://images.unsplash.com/photo-1612817288484-6f916006741a?w=600'],
    brand: 'COSRX',
    category: 'serum',
    skinType: ['oily', 'combination', 'sensitive'],
    concerns: ['pores', 'acne', 'redness', 'uneven-texture'],
    ingredients: ['niacinamide 10%', 'zinc PCA 1%', 'licorice root', 'allantoin'],
    stock: 130,
    rating: 4.5,
    numReviews: 267,
    isFeatured: false,
  },
  {
    name: 'Peptide Firming Serum',
    description: 'A multi-peptide complex that visibly firms, lifts, and plumps skin. Matrixyl 3000 and copper peptides stimulate collagen production for younger-looking skin.',
    price: 2599,
    compareAtPrice: 3099,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    brand: 'Deconstruct',
    category: 'serum',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'uneven-texture'],
    ingredients: ['matrixyl 3000', 'copper peptides', 'argireline', 'hyaluronic acid'],
    stock: 55,
    rating: 4.7,
    numReviews: 178,
    isFeatured: true,
  },
  {
    name: 'AHA/BHA Clarifying Serum',
    description: 'A dual-action exfoliating serum with 10% AHA and 2% BHA. Smooths rough texture, unclogs pores, and reveals fresh, glowing skin without irritation.',
    price: 1899,
    compareAtPrice: 2299,
    images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=600'],
    brand: 'Some By Mi',
    category: 'serum',
    skinType: ['combination', 'oily', 'normal'],
    concerns: ['acne', 'pores', 'uneven-texture', 'dullness'],
    ingredients: ['glycolic acid', 'lactic acid', 'salicylic acid 2%', 'centella asiatica'],
    stock: 80,
    rating: 4.6,
    numReviews: 212,
    isFeatured: false,
  },

  // ==================== TONERS ====================
  {
    name: 'Rose & Aloe Soothing Toner',
    description: 'An alcohol-free toner infused with damask rose water and aloe vera. Calms inflammation, balances pH, and preps skin for better serum absorption.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    brand: 'Plum',
    category: 'toner',
    skinType: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'dryness'],
    ingredients: ['rose water', 'aloe vera', 'glycerin', 'chamomile extract'],
    stock: 140,
    rating: 4.4,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'Glycolic Acid 7% Exfoliating Toner',
    description: 'A clarifying toner with 7% glycolic acid and AHAs. Exfoliates dead skin cells, smooths texture, and reveals brighter skin. Best used in PM routine.',
    price: 1699,
    compareAtPrice: 1999,
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600'],
    brand: 'The Ordinary',
    category: 'toner',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'uneven-texture', 'pores', 'dark-spots'],
    ingredients: ['glycolic acid 7%', 'lactic acid', 'aloe vera', 'ginseng'],
    stock: 88,
    rating: 4.6,
    numReviews: 203,
    isFeatured: false,
  },
  {
    name: 'Rice Water Brightening Toner',
    description: 'A milky toner enriched with fermented rice water (sake) and niacinamide. Brightens complexion, gently hydrates, and refines pores for a glass-skin effect.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    brand: 'Beauty of Joseon',
    category: 'toner',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dullness', 'dark-spots', 'pores'],
    ingredients: ['rice ferment filtrate', 'niacinamide', 'licorice extract', 'hyaluronic acid'],
    stock: 105,
    rating: 4.5,
    numReviews: 167,
    isFeatured: true,
  },
  {
    name: 'Centella Asiatica Calming Toner',
    description: 'A lightweight, watery toner packed with 80% centella asiatica extract. Instantly soothes redness, irritation, and strengthens the skin barrier. Ideal for sensitive, acne-prone skin.',
    price: 1499,
    compareAtPrice: 1799,
    images: ['https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600'],
    brand: 'SKIN1004',
    category: 'toner',
    skinType: ['sensitive', 'oily', 'combination'],
    concerns: ['redness', 'acne', 'dryness'],
    ingredients: ['centella asiatica 80%', 'madecassoside', 'panthenol', 'allantoin'],
    stock: 92,
    rating: 4.7,
    numReviews: 189,
    isFeatured: false,
  },

  // ==================== SUNSCREENS ====================
  {
    name: 'Invisible Sun Gel SPF 50 PA++++',
    description: 'An ultra-lightweight gel sunscreen with SPF 50 and PA++++. Zero white cast, non-sticky matte finish. Enriched with cica and hyaluronic acid.',
    price: 1599,
    compareAtPrice: 1899,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    brand: 'Aqualogica',
    category: 'sunscreen',
    skinType: ['oily', 'combination', 'normal', 'sensitive'],
    concerns: ['aging', 'dark-spots'],
    ingredients: ['centella asiatica', 'hyaluronic acid', 'niacinamide', 'UV filters'],
    stock: 150,
    rating: 4.8,
    numReviews: 487,
    isFeatured: true,
  },
  {
    name: 'Mineral Tinted Sunscreen SPF 50',
    description: 'A 100% mineral zinc oxide sunscreen with a universal tint. Reef-safe, non-nano, and suitable for the most sensitive skin including post-procedure.',
    price: 2199,
    compareAtPrice: 2499,
    images: ['https://images.unsplash.com/photo-1556229162-5c63ed9c4efb?w=600'],
    brand: 'Neutrogena',
    category: 'sunscreen',
    skinType: ['sensitive', 'dry', 'combination'],
    concerns: ['redness', 'aging'],
    ingredients: ['zinc oxide 18.5%', 'iron oxides', 'vitamin E', 'bisabolol'],
    stock: 75,
    rating: 4.7,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Water-Resistant Sport Sunscreen SPF 60',
    description: 'A high-performance, water-resistant sunscreen for outdoor activities and sports. Sweat-proof formula that stays put for up to 80 minutes in water without stinging eyes.',
    price: 1799,
    compareAtPrice: 2099,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    brand: 'Neutrogena',
    category: 'sunscreen',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['aging', 'dark-spots'],
    ingredients: ['avobenzone', 'homosalate', 'octisalate', 'vitamin E'],
    stock: 120,
    rating: 4.5,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'Daily Defense Moisturizer SPF 30',
    description: 'A 2-in-1 daily moisturizer with broad spectrum SPF 30. Lightweight lotion texture that hydrates and protects in one step — perfect for busy mornings.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1556229162-5c63ed9c4efb?w=600'],
    brand: 'Simple',
    category: 'sunscreen',
    skinType: ['normal', 'dry', 'sensitive'],
    concerns: ['aging', 'dryness'],
    ingredients: ['glycerin', 'ceramides', 'niacinamide', 'SPF filters'],
    stock: 140,
    rating: 4.4,
    numReviews: 189,
    isFeatured: false,
  },

  // ==================== MASKS ====================
  {
    name: 'Turmeric & Honey Brightening Mask',
    description: 'A creamy wash-off mask combining turmeric, raw honey, and kaolin clay. Detoxifies pores, brightens complexion, and fights inflammation naturally.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    brand: 'Pilgrim',
    category: 'mask',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['dullness', 'acne', 'pores'],
    ingredients: ['turmeric extract', 'honey', 'kaolin clay', 'yogurt extract'],
    stock: 90,
    rating: 4.5,
    numReviews: 176,
    isFeatured: false,
  },
  {
    name: 'Overnight Water Sleeping Mask',
    description: 'A leave-on gel mask that floods skin with hydration while you sleep. Wake up to plumper, dewier, well-rested looking skin with reduced fine lines.',
    price: 1499,
    compareAtPrice: 1799,
    images: ['https://images.unsplash.com/photo-1607434472257-d9f8e57a643d?w=600'],
    brand: 'COSRX',
    category: 'mask',
    skinType: ['dry', 'normal', 'combination'],
    concerns: ['dryness', 'dullness', 'aging'],
    ingredients: ['hyaluronic acid', 'trehalose', 'squalane', 'lavender oil'],
    stock: 82,
    rating: 4.6,
    numReviews: 234,
    isFeatured: false,
  },
  {
    name: 'Charcoal Detox Clay Mask',
    description: 'A deep-cleansing clay mask with activated charcoal and salicylic acid. Draws out impurities, blackheads, and excess sebum. Leaves skin smooth and matte.',
    price: 1099,
    compareAtPrice: 1399,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    brand: 'Plum',
    category: 'mask',
    skinType: ['oily', 'combination'],
    concerns: ['pores', 'acne', 'dullness'],
    ingredients: ['activated charcoal', 'kaolin clay', 'salicylic acid 1%', 'witch hazel'],
    stock: 95,
    rating: 4.4,
    numReviews: 154,
    isFeatured: false,
  },
  {
    name: 'Vitamin C Glow Sheet Mask (5 Pack)',
    description: 'A bio-cellulose sheet mask drenched in vitamin C and niacinamide essence. Instantly brightens, hydrates, and revives tired skin in just 15 minutes. Pack of 5.',
    price: 799,
    compareAtPrice: 999,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    brand: 'Faces Canada',
    category: 'mask',
    skinType: ['normal', 'dry', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'dryness'],
    ingredients: ['vitamin C', 'niacinamide', 'hyaluronic acid', 'glutathione'],
    stock: 180,
    rating: 4.5,
    numReviews: 267,
    isFeatured: true,
  },
  {
    name: 'Peel-Off Charcoal Glow Mask',
    description: 'A satisfying peel-off mask with activated charcoal and gold flakes. Removes blackheads, dead skin, and peach fuzz — revealing baby-soft, luminous skin underneath.',
    price: 899,
    compareAtPrice: 1199,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    brand: 'Faces Canada',
    category: 'mask',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['pores', 'dullness', 'acne'],
    ingredients: ['activated charcoal', 'gold flakes', 'aloe vera', 'vitamin E'],
    stock: 100,
    rating: 4.3,
    numReviews: 189,
    isFeatured: false,
  },

  // ==================== EYE CARE ====================
  {
    name: 'Caffeine Eye Serum',
    description: 'A lightweight eye serum with caffeine and peptides. Depuffs under-eye bags, brightens dark circles, and smooths fine lines around the delicate eye area.',
    price: 1799,
    compareAtPrice: 2199,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    brand: 'Minimalist',
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination', 'oily', 'sensitive'],
    concerns: ['aging', 'dullness', 'dryness'],
    ingredients: ['caffeine 5%', 'peptides', 'niacinamide', 'hyaluronic acid'],
    stock: 68,
    rating: 4.5,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Retinol Eye Repair Cream',
    description: 'A gentle retinol-infused eye cream that targets crow\'s feet, fine lines, and crepiness. Time-release technology ensures gradual delivery to minimize irritation.',
    price: 2199,
    compareAtPrice: 2599,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    brand: 'Deconstruct',
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'dryness'],
    ingredients: ['retinol 0.1%', 'peptides', 'ceramides', 'squalane'],
    stock: 55,
    rating: 4.6,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'Brightening Vitamin C Eye Cream',
    description: 'A rich eye cream with 5% vitamin C and kojic acid to fade dark circles. Light-reflecting minerals instantly brighten while the formula works long-term.',
    price: 1999,
    compareAtPrice: 2399,
    images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600'],
    brand: 'Foxtale',
    category: 'eye-care',
    skinType: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['dark-spots', 'dullness', 'aging'],
    ingredients: ['vitamin C 5%', 'kojic acid', 'caffeine', 'hyaluronic acid'],
    stock: 62,
    rating: 4.4,
    numReviews: 110,
    isFeatured: false,
  },
  {
    name: 'Cooling Eye Roller Gel',
    description: 'A gel formula with cucumber, aloe, and hyaluronic acid in a stainless steel rollerball. Instantly cools, depuffs, and wakes up tired eyes — perfect for mornings.',
    price: 1299,
    compareAtPrice: 1599,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    brand: 'Plum',
    category: 'eye-care',
    skinType: ['normal', 'oily', 'combination', 'sensitive'],
    concerns: ['dullness', 'dryness'],
    ingredients: ['cucumber extract', 'aloe vera', 'hyaluronic acid', 'caffeine'],
    stock: 100,
    rating: 4.3,
    numReviews: 98,
    isFeatured: false,
  },

  // ==================== LIP CARE ====================
  {
    name: 'Peptide Lip Recovery Balm',
    description: 'A nourishing lip balm with peptides and shea butter. Heals dry, chapped lips and restores the lip barrier. Tube packaging for easy, hygienic application.',
    price: 699,
    compareAtPrice: 899,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    brand: 'Foxtale',
    category: 'lip-care',
    skinType: ['normal', 'dry', 'oily', 'combination', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['peptides', 'shea butter', 'vitamin E', 'jojoba oil'],
    stock: 200,
    rating: 4.3,
    numReviews: 89,
    isFeatured: false,
  },
  {
    name: 'Overnight Lip Sleeping Mask',
    description: 'A rich, cushiony lip mask with berry complex and vitamin C. Melt away dead skin overnight and wake up to baby-soft, plump, hydrated lips by morning.',
    price: 899,
    compareAtPrice: 1199,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    brand: 'COSRX',
    category: 'lip-care',
    skinType: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['berry complex', 'vitamin C', 'hyaluronic acid', 'shea butter'],
    stock: 150,
    rating: 4.6,
    numReviews: 215,
    isFeatured: true,
  },
  {
    name: 'Tinted Lip Balm SPF 30',
    description: 'A sheer, buildable tinted lip balm with SPF 30 protection. Available in Rose Blush shade that adapts to your natural lip pH. Moisturizing with a hint of color.',
    price: 749,
    compareAtPrice: 949,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    brand: 'Faces Canada',
    category: 'lip-care',
    skinType: ['normal', 'dry', 'combination', 'oily', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['SPF 30 filters', 'argan oil', 'vitamin E', 'shea butter'],
    stock: 175,
    rating: 4.4,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'Lip Scrub & Balm Duo',
    description: 'A 2-step lip care set: gentle sugar exfoliator buffs away flakes, followed by a creamy balm to lock in moisture. Use 2-3 times weekly for smooth lips.',
    price: 1099,
    compareAtPrice: 1399,
    images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=600'],
    brand: 'Pilgrim',
    category: 'lip-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['dryness'],
    ingredients: ['sugar crystals', 'honey', 'shea butter', 'coconut oil'],
    stock: 85,
    rating: 4.5,
    numReviews: 123,
    isFeatured: false,
  },

  // ==================== BODY CARE ====================
  {
    name: 'AHA Body Smoothing Lotion',
    description: 'A body lotion with 10% AHA blend that smoothes rough bumps, keratosis pilaris, and strawberry skin. Leaves skin silky-soft with continued use.',
    price: 1399,
    compareAtPrice: 1699,
    images: ['https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600'],
    brand: 'Suganda',
    category: 'body-care',
    skinType: ['dry', 'normal'],
    concerns: ['uneven-texture', 'dryness', 'dullness'],
    ingredients: ['glycolic acid', 'lactic acid', 'shea butter', 'urea'],
    stock: 75,
    rating: 4.6,
    numReviews: 167,
    isFeatured: false,
  },
  {
    name: 'Whipped Shea Body Butter',
    description: 'An ultra-rich, whipped body butter with raw shea, cocoa butter, and coconut oil. Intensely nourishes extremely dry skin for up to 72 hours of moisture.',
    price: 1199,
    compareAtPrice: 1499,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    brand: 'Plum',
    category: 'body-care',
    skinType: ['dry', 'normal'],
    concerns: ['dryness', 'uneven-texture'],
    ingredients: ['raw shea butter', 'cocoa butter', 'coconut oil', 'vitamin E'],
    stock: 100,
    rating: 4.7,
    numReviews: 234,
    isFeatured: true,
  },
  {
    name: 'Body Sunscreen Spray SPF 50',
    description: 'A lightweight, non-greasy body sunscreen spray that provides broad spectrum SPF 50 protection. Quick-dry, water-resistant formula ideal for daily body protection.',
    price: 1699,
    compareAtPrice: 1999,
    images: ['https://images.unsplash.com/photo-1557202500-13e0ade5e466?w=600'],
    brand: 'Aqualogica',
    category: 'body-care',
    skinType: ['normal', 'oily', 'dry', 'combination'],
    concerns: ['aging', 'dark-spots'],
    ingredients: ['avobenzone', 'octocrylene', 'aloe vera', 'vitamin E'],
    stock: 115,
    rating: 4.4,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Repairing Hand & Nail Cream',
    description: 'A concentrated hand cream with shea butter, ceramides, and keratin. Repairs dry, cracked hands, strengthens nails, and restores cuticles. Non-greasy, fast-absorbing.',
    price: 799,
    compareAtPrice: 999,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    brand: 'Simple',
    category: 'body-care',
    skinType: ['normal', 'dry', 'sensitive'],
    concerns: ['dryness'],
    ingredients: ['shea butter', 'ceramides', 'keratin', 'vitamin E'],
    stock: 160,
    rating: 4.5,
    numReviews: 178,
    isFeatured: false,
  },
  {
    name: 'Coffee & Coconut Body Scrub',
    description: 'An invigorating body scrub with Arabica coffee grounds, coconut oil, and sea salt. Buffs away dead skin, stimulates circulation, and helps reduce the appearance of cellulite.',
    price: 999,
    compareAtPrice: 1299,
    images: ['https://images.unsplash.com/photo-1570194065650-d99fb4d8a609?w=600'],
    brand: 'Pilgrim',
    category: 'body-care',
    skinType: ['normal', 'dry', 'combination'],
    concerns: ['uneven-texture', 'dullness'],
    ingredients: ['coffee grounds', 'coconut oil', 'sea salt', 'sweet almond oil'],
    stock: 90,
    rating: 4.6,
    numReviews: 167,
    isFeatured: false,
  },

  // ==================== FACE CARE ====================
  {
    name: 'Rosehip Glow Face Oil',
    description: 'A lightweight, fast-absorbing face oil with cold-pressed rosehip, jojoba, and squalane. Rich in essential fatty acids that nourish, brighten, and restore radiance without clogging pores.',
    price: 1899,
    compareAtPrice: 2299,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    brand: 'Suganda',
    category: 'face-care',
    skinType: ['dry', 'normal', 'combination'],
    concerns: ['dullness', 'dryness', 'uneven-texture'],
    ingredients: ['rosehip oil', 'jojoba oil', 'squalane', 'vitamin E'],
    stock: 72,
    rating: 4.7,
    numReviews: 189,
    isFeatured: true,
  },
  {
    name: 'Green Tea Hydrating Face Mist',
    description: 'A refreshing, fine-mist spray infused with green tea, aloe, and hyaluronic acid. Instantly hydrates, soothes, and sets makeup. Use anytime your skin needs a boost.',
    price: 899,
    compareAtPrice: 1099,
    images: ['https://images.unsplash.com/photo-1601612628452-9e99ced43524?w=600'],
    brand: 'Simple',
    category: 'face-care',
    skinType: ['normal', 'dry', 'oily', 'combination', 'sensitive'],
    concerns: ['dryness', 'redness', 'dullness'],
    ingredients: ['green tea extract', 'aloe vera', 'hyaluronic acid', 'panthenol'],
    stock: 140,
    rating: 4.4,
    numReviews: 145,
    isFeatured: false,
  },
  {
    name: 'Gentle Walnut Face Scrub',
    description: 'A finely milled walnut shell face scrub with aloe vera and vitamin E. Buffs away dead skin cells, smoothes rough texture, and reveals glowing skin without micro-tears.',
    price: 1099,
    compareAtPrice: 1399,
    images: ['https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=600'],
    brand: 'Cetaphil',
    category: 'face-care',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['uneven-texture', 'dullness', 'pores'],
    ingredients: ['walnut shell powder', 'aloe vera', 'vitamin E', 'jojoba oil'],
    stock: 95,
    rating: 4.3,
    numReviews: 132,
    isFeatured: false,
  },
  {
    name: 'Sandalwood & Turmeric Face Pack',
    description: 'A traditional Ayurvedic face pack with sandalwood, turmeric, and multani mitti. Deeply cleanses, brightens complexion, controls oil, and leaves skin naturally glowing.',
    price: 799,
    compareAtPrice: 999,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    brand: 'The Derma Co',
    category: 'face-care',
    skinType: ['normal', 'oily', 'combination'],
    concerns: ['acne', 'dullness', 'pores'],
    ingredients: ['sandalwood powder', 'turmeric', 'multani mitti', 'neem extract'],
    stock: 110,
    rating: 4.5,
    numReviews: 198,
    isFeatured: false,
  },
  {
    name: 'Snail Mucin Repair Essence',
    description: 'A cult-favorite essence with 96% snail mucin filtrate. Repairs damaged skin, fades scars, boosts elasticity, and delivers intense hydration for a dewy, glass-skin finish.',
    price: 2299,
    compareAtPrice: 2799,
    images: ['https://images.unsplash.com/photo-1624454002302-36b824d7bd0a?w=600'],
    brand: 'COSRX',
    category: 'face-care',
    skinType: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['aging', 'uneven-texture', 'dryness', 'dark-spots'],
    ingredients: ['snail mucin 96%', 'hyaluronic acid', 'allantoin', 'panthenol'],
    stock: 50,
    rating: 4.8,
    numReviews: 312,
    isFeatured: true,
  },

  // ==================== SETS ====================
  {
    name: 'The Complete Routine Set',
    description: 'Our best-selling full routine in one box: Vitamin C Brightening Wash, Rose & Aloe Toner, Hyaluronic Acid Serum, Ceramide Barrier Repair Cream, and Invisible Sun Gel SPF 50.',
    price: 5499,
    compareAtPrice: 7499,
    images: ['https://images.unsplash.com/photo-1580870069867-74c57ee9bb07?w=600'],
    brand: 'CeraVe',
    category: 'set',
    skinType: ['normal', 'combination'],
    concerns: ['dullness', 'aging', 'dryness'],
    ingredients: ['multiple'],
    stock: 40,
    rating: 4.9,
    numReviews: 312,
    isFeatured: true,
  },
  {
    name: 'Anti-Aging Duo (Retinol + Collagen)',
    description: 'A powerful anti-aging duo featuring Retinol 0.5% Advanced Serum and Collagen Peptide Night Cream. The ultimate night routine for smoother, firmer, younger-looking skin.',
    price: 4299,
    compareAtPrice: 5599,
    images: ['https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=600'],
    brand: 'Minimalist',
    category: 'set',
    skinType: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'uneven-texture', 'dullness'],
    ingredients: ['retinol 0.5%', 'collagen peptides', 'bakuchiol', 'ceramides'],
    stock: 35,
    rating: 4.8,
    numReviews: 156,
    isFeatured: false,
  },
  {
    name: 'Glow Essentials Kit',
    description: 'Mini sizes of our most-loved glow products: Vitamin C 20% Serum (15ml), Gentle Hydrating Cleanser (50ml), and Invisible Sun Gel SPF 50 (30ml). Perfect for travel!',
    price: 3299,
    compareAtPrice: 4199,
    images: ['https://images.unsplash.com/photo-1596755389378-c31d21fd1273?w=600'],
    brand: 'The Ordinary',
    category: 'set',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'dark-spots', 'aging'],
    ingredients: ['multiple'],
    stock: 50,
    rating: 4.7,
    numReviews: 89,
    isFeatured: true,
  },
  {
    name: 'Starter Routine Kit',
    description: 'Everything a beginner needs: Gentle Hydrating Cleanser (100ml), Niacinamide 10% + Zinc Serum (30ml), Water Burst Gel Moisturizer (50g), and Invisible Sun Gel SPF 50 (30ml).',
    price: 2999,
    compareAtPrice: 3899,
    images: ['https://images.unsplash.com/photo-1580870069867-74c57ee9bb07?w=600'],
    brand: 'Cetaphil',
    category: 'set',
    skinType: ['normal', 'combination', 'oily'],
    concerns: ['dullness', 'pores', 'acne'],
    ingredients: ['multiple'],
    stock: 55,
    rating: 4.6,
    numReviews: 98,
    isFeatured: false,
  },
];

const seedProducts = async () => {
  try {
    const count = await Product.countDocuments();
    if (count > 0) {
      console.log(`Database already has ${count} products, skipping seed.`);
      return;
    }

    await Product.insertMany(products);
    console.log(`Seeded ${products.length} skincare products successfully.`);
  } catch (error) {
    console.error(`Seeding error: ${error.message}`);
  }
};

module.exports = seedProducts;
